// tslint:disable
/**
 * WebCrawler
 * This is a web crawler.
 *
 * OpenAPI spec version: 1.0.1-oas3
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
